   
- name:
  hosts: '{{ exa_host }}'
  tasks:

    - block:

      - name: 'Delete Working Copy'
        include_role:
          name: 'fpp_common'
          tasks_from: 'wc_delete.yml'
        vars:
          target_node: '{{ ansible_hostname }}'

      delegate_to: '{{ fpp_host }}'