 
- name:
  hosts: '{{ exa_group }}'
  tasks:

    - block:

      - name: 'Delete Image'
        include_role:
          name: 'fpp_common'
          tasks_from: 'image_delete.yml'
        vars:
          target_node: '{{ ansible_hostname }}'

      delegate_to: '{{ fpp_host }}'