- name:
  hosts: 'fpp'
  tasks:

    - name: 'Check Client Prerequistes'
      include_role:
        name: 'fpp_common'
        tasks_from: 'check_client_prereq.yml'

- name:
  hosts: '{{ hostgroup }}'
  tasks:
    
    - name: 'Patch GI Home'
      include_role:
        name: 'target_commands'
        tasks_from: 'patched_gi_zip.yml'

- name:
  hosts: 'fpp'
  tasks:
    
    - name: 'Create Map File'
      include_role:
        name: 'gi'
        tasks_from: 'gi_create_map_file.yml'
    
    - name: 'Register Image'
      include_role:
        name: 'gi'
        tasks_from: 'gi_register_image.yml'