- name:
  hosts: 'FPP'
  tasks:

    - name: 'Check Client Prerequistes'
      include_role:
        name: 'fpp_common'
        tasks_from: 'check_client_prereq.yml'

- name:
  hosts: '{{ hostgroup }}'
  tasks:
    
    # TO DO: when to know if we're using prexisting??
    - name: 'Create New GI Home'
      include_role:
        name: 'target_commands'
        tasks_from: 'create_gihome.yml'

- name:
  hosts: 'FPP'
  tasks:
    
    - name: 'Create Working Copy'
      include_role:
        name: 'fpp_rdbms'
        tasks_from: 'rdbms_create_wc.yml'

- name:
  hosts: '{{ hostgroup }}'
  tasks:
    
    - name: 'Purge Temp DB Home'
      include_role:
        name: 'target_commands'
        tasks_from: 'purge_dbhome.yml'