# This playbook creates and registers a new gi image. It will only need to be run 
# once per image so be sure the hostgroup specified only contains one cluster.

- name:
  hosts: '{{ fpp_host }}'
  tasks:

    - name: 'Check Client Prerequistes'
      include_role:
        name: 'fpp_common'
        tasks_from: 'check_client_prereq.yml'

- name:
  hosts: '{{ target_node }}'
  tasks:

    - set_fact:
        image_name: '{{ grid_version | regex.s'[0-9]+\.'

    - name: 'Update GI Home'
      include_role:
        name: 'target_commands'
        tasks_from: 'gihome_upgrade.yml'
    
    - name: 'Set Oracle Home to updated value'
      include_role:
        name: 'target_commands'
        tasks_from: 'oracle_home.yml'

    - name: 'Find Patch and Bug Data'
      include_role:
        name: 'target_commands'
        tasks_from: 'map_data.yml'

    - name: 'Find GI Groups'
      include_role:
        name: 'target_commands'
        tasks_from: 'map_groups.yml'
      vars:
        image_type: 'gi'

- name:
  hosts: '{{ fpp_host }}'
  tasks:
    
    - name: 'Create Map File'
      include_role:
        name: 'gi_role'
        tasks_from: 'gi_create_map_file.yml'
    
    - name: 'Register Image'
      include_role:
        name: 'gi_role'
        tasks_from: 'gi_register_image.yml'