# This playbook creates and registers a new gi image. It will only need to be run 
# once per image so be sure the hostgroup specified only contains one cluster.

- name:
  hosts: '{{ exa_host }}'
  tasks:
    
    - name: 'Assert general variables are defined.'
      assert:
        that: 
          - fpp_host is defined and identity_file is defined
          - container_url is defined
        quiet: 'true'

    - name: 'Check Client Prerequistes'
      import_role:
        name: 'fpp_common'
        tasks_from: 'check_client_prereq.yml'
      vars:
        target_node: '{{ ansible_hostname }}'
      delegate_to: '{{ fpp_host }}'

    - name: 'Set Current GI Home'
      include_role:
        name: 'grid_fpp'
        tasks_from: 'gi_image_create.yml'