- name:
  hosts: 'FPP'
  tasks:

    - name: 'Check Client Prerequistes'
      include_role:
        name: 'fpp_common'
        tasks_from: 'check_client_prereq.yml'

- name:
  hosts: '{{ hostgroup_exadata }}'
  tasks:
    
    - name: 'Patch GI Home'
      include_role:
        name: 'target_commands'
        tasks_from: 'patch_gi.yml'

# TO DO: Create GI Home Zip File
# Upload Encrypted File to Object Storage

- name:
  hosts: 'FPP'
  tasks:
    
    - name: 'Create Map File'
      include_role:
        name: 'fpp_gi'
        tasks_from: 'gi_create_map_file.yml'
    
    - name: 'Register Image'
      include_role:
        name: 'fpp_gi'
        tasks_from: 'gi_register_image.yml'