
- name:
  hosts: '{{ fpp_host }}'
  tasks:

    - name: 'Check Client Prerequistes'
      include_role:
        name: 'fpp_common'
        tasks_from: 'check_client_prereq.yml'

- name:
  hosts: '{{ exa_hosts }}'
  tasks:
    
    - name: 'Create New GI Home'
      include_role:
        name: 'target_commands'
        tasks_from: 'create_gihome.yml'
      vars:
        dbhome_name: 'wc_{{ image_name }}_{{ cluster_name }}'
    
    - name: 'Find GI Groups'
      when: osdbagrp_groups is not defined
      include_role:
        name: 'target_commands'
        tasks_from: 'map_groups.yml'
      vars:
        image_type: 'grid'
        target_user: 'grid'


- name:
  hosts: '{{ fpp_host }}'
  tasks:
    
    - name: 'Create Working Copy'
      include_role:
        name: 'gi_role'
        tasks_from: 'gi_create_wc.yml'