
- name:
  hosts: '{{ exa_group }}'
  tasks:
    
    - name: 'Assert general variables are defined.'
      assert:
        that: 
          - fpp_host is defined
          - identity_file is defined
          - container_url is defined
        quiet: 'true'

    - name: 'Check Client Prerequistes'
      import_role:
        name: 'fpp_common'
        tasks_from: 'check_client_prereq.yml'
      vars:
        target_node: '{{ ansible_hostname }}'
      delegate_to: '{{ fpp_host }}'

    - assert:
        that: 
          - image_name is defined
          - gi_home_path is defined

    - name: 'Add GI Working Copy'
      include_role:
        name: 'grid_fpp'
        tasks_from: 'gi_wc_create.yml'
      vars:
        existing_home: true
