# This playbook creates and registers a new gi image. It will only need to be run 
# once per image so be sure the hostgroup specified only contains one cluster.


- name:
  hosts: '{{ gi_host }}'
  vars:
    target_user: 'grid'
  tasks:
    
    - name: 'Update GI Home and Zip'
      include_role:
        name: 'target_commands'
        tasks_from: 'gihome_zip.yml'
    
    - name: 'Set Oracle Home to updated value'
      include_role:
        name: 'target_commands'
        tasks_from: 'oracle_home.yml'
      vars:
        db_regex: '+ASM[0-9]'
      when: oracle_home is not defined

    - name: 'Find Patch and Bug Data'
      include_role:
        name: 'target_commands'
        tasks_from: 'map_data.yml'

    - name: 'Find GI Groups'
      include_role:
        name: 'target_commands'
        tasks_from: 'map_groups.yml'
      vars:
        image_type: 'grid'

- name:
  hosts: '{{ fpp_host }}'
  tasks:
    
    # - name: 'Check Client Prerequistes'
    #   include_role:
    #     name: 'fpp_common'
    #     tasks_from: 'check_client_prereq.yml'

    - name: 'Create Map File'
      include_role:
        name: 'gi_role'
        tasks_from: 'gi_create_map_file.yml'
    
    - name: 'Register Image'
      include_role:
        name: 'gi_role'
        tasks_from: 'gi_register_image.yml'