# This playbook creates and registers a new gi image. It will only need to be run 
# once per image so be sure the hostgroup specified only contains one cluster.

- name:
  hosts: '{{ exa_host }}'
  tasks:
    
    - block:

      - name: 'Check Client Prerequistes'
        include_role:
          name: 'fpp_common'
          tasks_from: 'check_client_prereq.yml'
        vars:
          target_node: '{{ ansible_hostname }}'

       # TO DO: Finalize Fiserv Naming Standards
      - set_fact:
          image_name: 'gihome1_{{ grid_version | regex_replace("\.", "") }}'
        when: image_name is not defined
      - debug:
          var: image_name

      - name: 'Check if Image {{ image_name }} Exists'
        include_role:
          name: 'fpp_common'
          tasks_from: 'image_query.yml'
        vars:
          ignore_errors_flag: 'yes'
      - fail:
          msg: 'Image with name {{ image_name }} already exists. Run again with custom image_name provided.'
        when: not query_image_result.stdout | regex_search("does not exist")
      
      delegate_to: '{{ fpp_host }}'
    

    - name: 'Set Current GI Home'
      include_role:
        name: 'target_commands'
        tasks_from: 'gihome_path.yml'

    # # TO DO: Test out Upgrade
    # - name: 'Upgrade GI Home'
    #   include_role:
    #     name: 'target_commands'
    #     tasks_from: 'gihome_upgrade.yml'
    
    - name: 'Zip GI Home'
      include_role:
        name: 'target_commands'
        tasks_from: 'gihome_zip.yml'

    - name: 'Create Map File'
      include_role:
        name: 'gi_role'
        tasks_from: 'gi_create_map_file.yml'
  
    - name: 'Register Image'
      include_role:
        name: 'gi_role'
        tasks_from: 'gi_register_image.yml'