
- name:
  hosts: 'fpp'
  tasks:

    - name: 'Check Client Prerequistes'
      include_role:
        name: 'fpp_common'
        tasks_from: 'check_client_prereq.yml'

- name:
  hosts: '{{ hostgroup }}'
  tasks:
    
    - name: 'Create New GI Home'
      include_role:
        name: 'target_commands'
        tasks_from: 'create_gihome.yml'
      vars:
        dbhome_name: 'wc_{{ image_name }}_{{ cluster_name }}'
    
    - name: 'Find GI Groups'
      include_role:
        name: 'target_commands'
        tasks_from: 'map_data_groups.yml'

- name:
  hosts: 'fpp'
  tasks:
    
    - name: 'Create Working Copy'
      include_role:
        name: 'gi_role'
        tasks_from: 'gi_create_wc.yml'