
- name:
  hosts: '{{ exa_host }}'
  tasks:
    
    - block:
      
      - name: 'Check Client Prerequistes'
        include_role:
          name: 'fpp_common'
          tasks_from: 'check_client_prereq.yml'
        vars:
          target_node: '{{ ansible_hostname }}'
      
      - name: 'Check if Source Home is WC'
        include_role:
          name: 'fpp_common'
          tasks_from: 'wc_query.yml'
        vars:
          wc_name: '{{ source_wc }}'
        when: (source_wc is defined) and (source_home_flag is not defined or source_home_flag == 'false')

      - name: 'Check if New Home is WC'
        include_role:
          name: 'fpp_common'
          tasks_from: 'wc_query.yml'
        vars:
          wc_name: '{{ dest_wc }}'
      
      delegate_to: '{{ fpp_host }}'

    - name: 'Patch GI'
      include_role:
        name: 'gi_role'
        tasks_from: 'gi_patch_grid.yml'
