
- name:
  hosts: '{{ fpp_host }}'
  tasks:

    - name: 'Check Client Prerequistes'
      include_role:
        name: 'fpp_common'
        tasks_from: 'check_client_prereq.yml'

- name:
  hosts: '{{ exa_host }}'
  tasks:
    
    - name: 'Set GI Home'
      include_role:
        name: 'target_commands'
        tasks_from: 'gihome_path.yml'
      when: source_wc is not defined and source_home_flag is defined and source_home_flag == 'true'

- name:
  hosts: '{{ fpp_host }}'
  tasks:
    
    - name: 'Check if Source Home is WC'
      include_role:
        name: 'fpp_common'
        tasks_from: 'wc_query.yml'
      vars:
        wc_name: '{{ source_wc }}'
      when: (source_wc is defined) and (source_home_flag is not defined or source_home_flag == 'false')

    - name: 'Check if New Home is WC'
      include_role:
        name: 'fpp_common'
        tasks_from: 'wc_query.yml'
      vars:
        wc_name: '{{ dest_wc }}'

    - name: 'Patch GI'
      include_role:
        name: 'gi_role'
        tasks_from: 'gi_patch_grid.yml'
