# This playbook creates and registers a new rdbms image. It will only need to be run once 
# per image so be sure the hostgroup specified only contains one cluster.

- name:
  hosts: 'fpp'
  tasks:

    - name: 'Check Client Prerequistes'
      include_role:
        name: 'fpp_common'
        tasks_from: 'check_client_prereq.yml'

- name:
  hosts: '{{ hostgroup }}'
  tasks:
    
    - name: 'Create Temp DB Home'
      include_role:
        name: 'target_commands'
        tasks_from: 'dbhome_create.yml'
      vars:
        dbhome_name: 'temp4image1'
    
    - name: 'Check Temp DB Home'
      include_role:
        name: 'target_commands'
        tasks_from: 'dbhome_info.yml'
      vars:
        dbhome_name: 'temp4image1'
    
    # TO do: figure out image name

    - name: 'Find Patch and Bug Data'
      include_role:
        name: 'target_commands'
        tasks_from: 'map_patch.yml'

    - name: 'Find DB Groups'
      include_role:
        name: 'target_commands'
        tasks_from: 'map_groups.yml'
      vars:
        image_type: 'db'


- name:
  hosts: 'fpp'
  tasks:
    
    - name: 'Create Map File'
      include_role:
        name: 'rdbms_role'
        tasks_from: 'rdbms_create_map_file.yml'
    
    - name: 'Register Image'
      include_role:
        name: 'rdbms_role'
        tasks_from: 'rdbms_register_image.yml'

- name:
  hosts: '{{ hostgroup }}'
  tasks:

    - name: 'Purge Temp DB Home'
      include_role:
        name: 'target_commands'
        tasks_from: 'purge_dbhome.yml'
      vars:
          dbhome_name: 'temp4image1'