
- name:
  hosts: '{{ fpp_host }}'
  tasks:

    - block:
      - name: 'Check Client Prerequistes'
        include_role:
          name: 'fpp_common'
          tasks_from: 'check_client_prereq.yml'
      
      - name: 'Check if Source Home is WC'
        include_role:
          name: 'fpp_common'
          tasks_from: 'wc_query.yml'
        vars:
          wc_name: 'wc_{{ source_image }}_{{ cluster_name }}'
      
      - name: 'Check if New Home is WC'
        include_role:
          name: 'fpp_common'
          tasks_from: 'wc_query.yml'
        vars:
          wc_name: 'wc_{{ image_name }}_{{ cluster_name }}'
    when: check_prereq is defined and check_prereq == 'true'

    - name: 'Patch Database'
      include_role:
        name: 'rdbms'
        tasks_from: 'rdbms_patch.yml'


- name:
  hosts: '{{ exadata_host }}'
  tasks:

    - name: 'Check Database'
      include_role:
        name: 'target_commands'
        tasks_from: 'dbhome_info.yml'
    
    # TO do: Check output for software: yes