# Creates and adds a new RDBMS working copy. Run once per vm cluster - exa_group should include one node per cluster. 
# Required variables: fpp_host, identity_file, exa_group, image_name, version, version_tag

- name:
  hosts: '{{ exa_group }}'
  tasks:

    - name: 'Assert required variables are defined.'
      assert:
        that: 
          - fpp_host is defined and identity_file is defined
          - image_name is defined and version is defined and version_tag is defined
        quiet: 'true'
      run_once: 'true'

    - name: 'Check Client Prerequistes'
      import_role:
        name: 'fpp_common'
        tasks_from: 'check_client_prereq.yml'
      vars:
        target_node: '{{ ansible_host }}'
      delegate_to: '{{ fpp_host }}'
    
    - name: 'Create RDBMS WC'
      include_role:
        name: 'rdbms_fpp'
        tasks_from: 'rdbms_wc_create.yml'

      

    