- name:
  hosts: 'fpp'
  tasks:

    - name: 'Check Client Prerequistes'
      include_role:
        name: 'fpp_common'
        tasks_from: 'check_client_prereq.yml'

- name:
  hosts: '{{ hostgroup }}'
  tasks:
    
    - name: 'Create New DB Home'
      include_role:
        name: 'target_commands'
        tasks_from: 'create_dbhome.yml'
      when: prexisting == 'false'         # prexisting will be true only for initial setup, to convert existing homes to wc.

    # TO DO: will have to query ORACLE_HOME to pull group data. Or, could change current method to pull from map file.
    - name: 'Find DB Groups'
      include_role:
        name: 'target_commands'
        tasks_from: 'map_data_groups.yml'

- name:
  hosts: 'fpp'
  tasks:
    
    - name: 'Create Working Copy'
      include_role:
        name: 'rdbms_role'
        tasks_from: 'rdbms_create_wc.yml'