# This playbook adds a new working copy. It will need to be run once per dbhome per cluster. 
# Create New DB Home (to be used for working copy) will only run if prexisting is false.
# Prexisting should be true only for initial setup, to convert existing homes to wc. 

- name:
  hosts: 'fpp'
  tasks:

    - name: 'Check Client Prerequistes'
      include_role:
        name: 'fpp_common'
        tasks_from: 'check_client_prereq.yml'

- name:
  hosts: '{{ hostgroup }}'
  tasks:
    
    # TO DO: QUERY TO MAKE SURE WC IS UNIQUE - Set new name if not unique

    - set_fact:
        wc_name: 'wc_{{ image_name }}_{{ cluster_name }}'

    - name: 'Create New DB Home'
      include_role:
        name: 'target_commands'
        tasks_from: 'create_dbhome.yml'
      vars:
        dbhome_name: '{{ wc_name }}'
      when: prexisting == 'false'

    # TO DO: make sure we should be doing this twice and not using image information?
    - name: 'Find DB Groups'
      include_role:
        name: 'target_commands'
        tasks_from: 'map_data_groups.yml'

- name:
  hosts: 'fpp'
  tasks:
    
    - name: 'Create Working Copy'
      include_role:
        name: 'rdbms_role'
        tasks_from: 'rdbms_create_wc.yml'