- name:
  hosts: 'FPP'
  tasks:

    - name: 'Check Client Prerequistes'
      include_role:
        name: 'fpp_common'
        tasks_from: 'check_client_prereq.yml'
      vars:
        identity_file: 'path_to_key'
        target_cluster_node: 'target_node'

- name:
  hosts: '{{ hostgroup_exadata }}'
  tasks:
    
    - name: 'Create Temp DB Home'
      include_role:
        name: 'target_commands'
        tasks_from: 'create_dbhome.yml'
      vars:
        dbhome_name: 'temp4image'
    
    - name: 'Pull Map Values'
      include_role:
        name: 'target_commands'
        tasks_from: 'map_determinations.yml'


- name:
  hosts: 'FPP'
  tasks:
    
    - name: 'Create Map File'
      include_role:
        name: 'fpp_rdbms'
        tasks_from: 'rdbms_create_map_file.yml'
    
    - name: 'Register Image'
      include_role:
        name: 'fpp_rdbms'
        tasks_from: 'rdbms_register_image.yml'

- name:
  hosts: '{{ hostgroup_exadata }}'
  tasks:
    
    - name: 'Purge Temp DB Home'
      include_role:
        name: 'target_commands'
        tasks_from: 'purge_dbhome.yml'
      vars:
          dbhome_name: 'temp4image'