   
- name:
  hosts: '{{ exa_group }}'
  tasks:

    - block:

      - name: 'Delete Working Copy'
        include_role:
          name: 'fpp_common'
          tasks_from: 'wc_delete.yml'
        vars:
          target_node: '{{ ansible_hostname }}'

      delegate_to: '{{ fpp_host }}'
    
    - name: 'Delete Home in Console'
      include_role:
        name: 'rdbms_role'
        tasks_from: 'rdbms_delete_home.yml'
      vars:
        dbhome_name: '{{ wc_name }}'