- name:
  hosts: 'localhost'
  tasks:
  
  - set_fact:
      output_test: '-rwsr-s--x 1 crsusr oinstall 425342368 Feb 21 06:56 /scratch/u02/home/bin/oracle'    
  - set_fact:
      gi_user: '{{ output_test.split(" ")[2] }}'
  - debug:
      var: gi_user