# This playbook creates and registers a new rdbms image. It will only need to be run once 
# per image so be sure the hostgroup specified only contains one cluster.

- name:
  hosts: '{{ exa_host }}'
  tasks:
    
    - name: 'Check if DB Unique Name is valid'
      become: true
      become_user: 'root'
      become_method: 'sudo'
      shell: 'grep {{ db_unique_name }}: /etc/oratab'
      ignore_errors: 'yes'
      register: 'unique_result'
    - fail:
        msg: 'Database not valid.'
      when: not unique_result.stdout | regex_search(db_unique_name)
