# This playbook creates and registers a new rdbms image. It will only need to be run once 
# per image so be sure the hostgroup specified only contains one cluster.

- name:
  hosts: '{{ exa_group }}'
  tasks:
    
    - name: List db_home_patches
      debug:
        msg: 'true'
      when: 19.13.0.0.0 > 19.10.0.0

