# This playbook creates and registers a new rdbms image. It will only need to be run once 
# per image so be sure the hostgroup specified only contains one cluster.

- name:
  hosts: '{{ exa_group }}'
  tasks:
    
    - name: 'Create Working Copy'
      include_role:
        name: 'target_commands'
        tasks_from: 'gihome_path.yml'

