- name: 'Check if DB Unique Name {{ db_unique_name }} is valid'
  become: 'true'
  become_user: 'root'
  become_method: 'sudo'
  shell: |
    grep "{{ db_unique_name }}" /etc/oratab
  register: 'db_name_result'