# TO EDIT: exacs.props path - change portion tbat is currently /opt/oracle/exacs.props

- name: 'ExaCS VM Cluster OCID'
  become: 'true'
  become_user: 'root'
  become_method: 'sudo'
  shell: |
    grep vmcluster_ocid= {{ exacs_props_path }}
  register: 'exacs_vm_cluster_ocid'
- debug: { msg: '{{ exacs_vm_cluster_ocid }}' }
- set_fact:
    vm_cluster_id: '{{ exacs_vm_cluster_ocid.stdout | regex_findall("vmcluster_ocid=(.+)") | first }}'