
- name: 'Get Inventory Location'
  become: 'true'
  become_user: 'root'
  become_method: 'sudo'
  shell:  |
    grep inventory_loc /etc/oraInst.loc
  register: 'inventory_result'
- set_fact:
    inventory_path: '{{ inventory_result.stdout | regex_findall("inventory_loc=(.+)") | first }}'
- debug: { var: 'inventory_path' }

- name: 'Get Active Grid Home'
  become: 'true'
  become_user: 'root'
  become_method: 'sudo'
  shell:  |
    grep 'CRS="true"' {{ inventory_path }}/ContentsXML/inventory.xml
  register: 'crs_path_result'
- debug: { msg: '{{ crs_path_result }}' }
- set_fact:
    oracle_home: '{{ crs_path_result.stdout | regex_findall("LOC=.(/.+?). ") | first }}'
- debug: { var: 'oracle_home' }

# used for gi wc create
- name: 'Get Client Name'
  become: 'true'
  become_user: 'grid'
  become_method: 'sudo'
  shell:  |
    {{ oracle_home }}/bin/olsnodes -c
  register: 'client_name_result'
- debug:
    msg: '{{ client_name_result }}'
- set_fact:
    client_name: '{{ client_name_result.stdout }}'
- debug: { var: 'client_name' }






