
- name: 'Assert RDBMS Create Image Variables are defined'
  assert:
    that: version is defined and version_tag is defined
    quiet: 'true'

# Set image name and check if it already exists

- set_fact:
    ru_version_string: '{{ version_tag | regex_replace("\.", "") }}'
# TO EDIT: image_name - RDBMS image naming convention
- set_fact:
    image_name: 'DB{{ ru_version_string[:6] }}'
  when: image_name is not defined
- debug: { var: image_name }

- block:
  - name: 'Check if Image {{ image_name }} Exists'
    include_role:
      name: 'fpp_common'
      tasks_from: 'image_query.yml'
    vars:
      ignore_errors_flag: 'yes'
  - fail:
      msg: 'Image with name {{ image_name }} already exists. Run again with custom image_name provided.'
    when: not query_image_result.stdout | regex_search("does not exist")
  delegate_to: '{{ fpp_host }}'

# Creates temp home to query for image information and sets oracle home
# If any errors post creation, will delete temp home

- set_fact:
    temp_db_home_name: 'tmp{{ ru_version_string[:5] }}img'

- name: 'Create fresh {{ version_tag }} DB Home'
  include_role:
    name: 'target_common'
    tasks_from: 'dbhome_create.yml'
  vars:
    db_home_name: '{{ temp_db_home_name }}'

- name: 'Always delete temp home, even if errors occur.'
  block:

  # Create map file and register image

  - name: 'Assert that oracle_home is defined.'
    assert: 
      that: oracle_home is defined
      quiet: 'true'

  - name: 'Create Map File'
    include_tasks: 'rdbms_image_map.yml'
    
  - name: 'Register Image'
    include_tasks: 'rdbms_image_register.yml'

  always:
  
  # Always delete temp home

  - name: 'Purge dbhome'
    include_role:
      name: 'target_common'
      tasks_from: 'dbhome_purge.yml'
    vars:
      db_home_name: '{{ temp_db_home_name }}'

  - name: 'Find VM Cluster OCID'
    include_role:
      name: 'target_common'
      tasks_from: '{{ exadata_type }}_ocid.yml'

  - name: 'Run from localhost with OCI authentication'
    block:
    
    - block:
      - name: 'Delete Temp DB Home'
        include_role:
          name: 'oci_common'
          tasks_from: 'db_home_delete.yml'
        vars:
          db_home_name: '{{ temp_db_home_name }}'
    
      rescue:
      - fail:
          msg: 'Delete operation failed.'
        when: db_home_discovery_result.db_homes|length != 0
      - debug: { msg: 'Operation succeeded. {{ temp_db_home_name }} not synced to console.' }
        
    delegate_to: localhost