
# TO EDIT - naming standards
- set_fact:
    wc_name: 'wc{{ db_home_name | regex_findall("dbhome([0-9].+)") | first }}_{{ ansible_hostname | regex_findall("(.+?)-") | first }}'

- block:
  - name: 'Check if WC Exists'
    include_role:
      name: 'fpp_common'
      tasks_from: 'wc_query.yml'
  delegate_to: '{{ fpp_host }}'