
- name: 'Assert RDBMS Create Image Variables are defined.'
  assert: { that: version is defined and version_tag is defined }

# Set Image Name and Check if Exists
- set_fact:
    ru_version_string: '{{ version_tag | regex_replace("\.", "") }}'
# NAMING STANDARD
- set_fact:
    image_name: 'DB2{{ ru_version_string[:6] }}'
  when: image_name is not defined
- debug: { var: image_name }

- block:
  - name: 'Check if Image {{ image_name }} Exists'
    include_role:
      name: 'fpp_common'
      tasks_from: 'image_query.yml'
    vars:
      ignore_errors_flag: 'yes'
  - fail:
      msg: 'Image with name {{ image_name }} already exists. Run again with custom image_name provided.'
    when: not query_image_result.stdout | regex_search("does not exist")
  delegate_to: '{{ fpp_host }}'

# Creates temp DB and sets oracle home.

- name: 'Create fresh {{ version_tag }} DB Home'
  include_role:
    name: 'target_commands'
    tasks_from: 'dbhome_create.yml'
  vars:
    db_home_name: '{{ temp_db_home_name }}'

- name: 'Always delete temp home, even if errors occur.'
  block:

  - assert: { that: oracle_home is defined }

  - name: 'Create Map File'
    include_tasks: 'rdbms_image_map.yml'
    
  - name: 'Register Image'
    include_tasks: 'rdbms_image_register.yml'

  always:
  
  - name: 'Purge dbhome'
    include_role:
      name: 'target_commands'
      tasks_from: 'dbhome_purge.yml'
    vars:
        db_home_name: '{{ temp_db_home_name }}'

  - name: 'Find VM Cluster OCID'
    include_role:
      name: 'target_commands'
      tasks_from: '{{ exadata_type }}_ocid.yml'

  - block:
    - name: 'Delete Temp DB Home'
      include_role:
        name: 'oci_tasks'
        tasks_from: 'db_home_delete.yml'
      ignore_errors: 'true'
      vars:
        db_home_name: '{{ temp_db_home_name }}'
    delegate_to: localhost