
- assert: { that: image_name is defined and version is defined and ru_version is defined }

# TO DO: Finalize Naming Conventions
- set_fact:
    wc_name: 'multiple1_{{ image_name }}_{{ ansible_hostname[:-2] }}'
  when: wc_name is not defined

- name: 'Check if WC Exists'
  import_role:
    name: 'fpp_common'
    tasks_from: 'wc_query.yml'
  vars:
    ignore_errors_flag: 'yes'
  delegate_to: '{{ fpp_host }}'
- fail:
    msg: 'Working copy with name {{ wc_name }} already exists. Run on {{ ansible_hostname }} again with custom wc_name provided.'
  when: not query_wc_result.stdout | regex_search("does not exist")
  
- name: 'Find VM Cluster OCID'
  include_role:
    name: 'target_commands'
    tasks_from: '{{ exadata_type }}_ocid.yml'

- name: 'Create DB Home'
  import_role:
    name: 'oci_tasks'
    tasks_from: 'db_home_create.yml'
  vars:
    db_home_name: '{{ wc_name }}'
    db_version: '{{ version }}'
  delegate_to: localhost
- assert: { that: oracle_home is defined }

- name: 'Create Working Copy'
  include_role:
    name: 'rdbms_fpp'
    tasks_from: 'rdbms_wc_add.yml'