- name: 'Assert RDBMS Create Image Variables are defined.'
  assert: 
    that: db_unique_name is defined source_home is defined and dest_home is defined
    quiet: 'true'

- name: 'Assert that patch_error_param is expected value.'
  assert:
    that:
      - patch_error_param == '-revert' or patch_error_param == '-continue'
    quiet: 'true'
  when: patch_error_param is defined

- name: 'Assert that ignorewcpatches_param is expected value.'
  assert:
    that: ignorewcpatches_param == '-ignorewcpatches' or ignorewcpatches_param == ''
    quiet: 'true'

- name: 'Assert that forcerolling_param is expected value.'
  assert:
    that: forcerolling_param == '-forcerolling' or forcerolling_param == ''
    quiet: 'true'

- name: 'Check if DB Unique Name is valid'
  include_role:
    name: 'target_common'
    tasks_from: 'db_unique_name.yml'

- name: 'Delegating to FPP Host'
  block:
  
  - name: 'Run Prereqs if No Retry'
    block:

    - name: 'Check if Source Home is WC'
      include_tasks: 'rdbms_wc_name.yml'
      vars:
        db_home_name: '{{ source_home }}'
    - set_fact:
        source_wc: '{{ wc_name }}'

    - name: 'Check if Dest Home is WC'
      include_tasks: 'rdbms_wc_name.yml'
      vars:
        db_home_name: '{{ dest_home }}'
    - set_fact:
        dest_wc: '{{ wc_name }}'

    - name: 'Patch Database {{ db_unique_name }} EVAL'
      include_role:
        name: 'fpp_common'
        tasks_from: 'patch.yml'
      vars:
        target_node: '{{ ansible_hostname }}'
        eval_param: '-eval'
    
    when: patch_error_param is not defined

  - name: 'Patch Database {{ db_unique_name }}'
    include_role:
      name: 'fpp_common'
      tasks_from: 'patch.yml'
    vars:
      target_node: '{{ ansible_hostname }}'
  
  delegate_to: '{{ fpp_host }}'
