
- block:
  - name: 'Register RDBMS Image {{ image_name }}'
    include_role:
      name: 'fpp_common'
      tasks_from: 'image_register.yml'
    vars:
      image_map_dir: 'db'   # development note: this should be the default path for rdbms maps on FPP. If running into errors, may need to update dir name
      software_type: 'ORACLEDBSOFTWARE'

  - name: 'Query RDBMS Image {{ image_name }}'
    include_role:
      name: 'fpp_common'
      tasks_from: 'image_query.yml'
  delegate_to: '{{ fpp_host }}'