- name: 'Assert RDBMS Create Image Variables are defined.'
  assert: { that: db_unique_name is defined and source_home is defined and dest_home is defined }

- name: 'Check if DB Unique Name is valid'
  become: true
  become_user: 'root'
  become_method: 'sudo'
  shell: 'grep {{ db_unique_name }}: /etc/oratab'
  ignore_errors: 'yes'
  register: 'db_name_result'
- fail:
    msg: 'Database not valid.'
  when: not db_name_result.stdout | regex_search(db_unique_name)

- name: 'Check if Source Home is WC'
  include_tasks: 'get_wc_name.yml'
  vars:
    ignore_errors_flag: 'no'
    db_home_name: '{{ source_home }}'
- set_fact:
    source_wc: '{{ wc_name }}'

- name: 'Check if Dest Home is WC'
  include_tasks: 'get_wc_name.yml'
  vars:
    ignore_errors_flag: 'no'
    db_home_name: '{{ dest_home }}'
- set_fact:
    dest_wc: '{{ wc_name }}'

- name: 'Patch Database {{ db_unique_name }} EVAL'
  import_role:
    name: 'fpp_common'
    tasks_from: 'patch.yml'
  vars:
    target_node: '{{ ansible_hostname }}'
    move_type: 'database'
    dest_param: '-patchedwc {{ dest_wc }}'
    db_param: '-dbname {{ db_unique_name }}'
    ignorewcpatches_param: ''
    forcerolling_param: ''
    eval_param: '-eval'
  delegate_to: '{{ fpp_host }}'
  when: retry is not defined or retry == 'false'

- name: 'Patch Database {{ db_unique_name }}'
  import_role:
    name: 'fpp_common'
    tasks_from: 'patch.yml'
  vars:
    target_node: '{{ ansible_hostname }}'
    move_type: 'database'
    dest_param: '-patchedwc {{ dest_wc }}'
    db_param: '-dbname {{ db_unique_name }}'
    ignorewcpatches_param: ''
    forcerolling_param: ''
    eval_param: ''
  delegate_to: '{{ fpp_host }}'

# TO DO: Check if successful