

- name: 'Add RDBMS Workingcopy {{ workingcopy }}'
  include_role:
    name: 'fpp_common'
    tasks_from: 'add_wc.yml'
  vars:
    add_wc_parameters: '-skipclone -oraclebase /{{ user_mount_point }}/app/oracle -user oracle'
  register: 'add_rdbms_wc_result'
- debug:
    msg: '{{ add_rdbms_wc_result }}'

query workingcopy