# TO DO: Update Paths from Test Node to FPP

- name: 'Add Map File'
  include_role:
    name: 'fpp_common'
    tasks_from: 'copy_map.yml'
  vars:
    location: '/root/tmp/db/{{ image_name }}.map'
    image_type: 'db'