
- name: 'Find Patch and Bug Data'
  include_role:
    name: 'target_commands'
    tasks_from: 'map_data.yml'
  vars:
    target_user: 'oracle'

- name: 'Find DB Groups'
  include_role:
    name: 'target_commands'
    tasks_from: 'map_groups.yml'
  vars:
    image_type: 'db'
    target_user: 'oracle'

- set_fact:
    ru_version_tag: '{{ ru_version | regex_replace("\.", "") }}'

- name: 'Add Map File'
  import_role:
    name: 'fpp_common'
    tasks_from: 'map_file_create.yml'
  vars:
    target_node: '{{ ansible_hostname }}'
    image_type: 'db'
    image_map_path: 'maps/db'
    image: '{{ image_name }}.zip.gpg'
    image_tag: '{{ ru_version_tag[:5] }}EE'    # TO TEST
    ru_version: '{{ ru_version }}'   # Development Note: Choosing to set map ru_version to match dbaascli dbhome info output. Might not match OCI standards.
    patches: '{{ patch_numbers }}'
    osdbagrp_groups: '{{ osdbagrp_groups }}'
  delegate_to: '{{ fpp_host }}'

# - name: 'Add Map File'
#   include_role:
#     name: 'fpp_common'
#     tasks_from: 'map_file_create.yml'
#   vars:
#     image_type: 'db'
#     image_map_path: 'maps/db'
#     image: '{{ image_name }}.zip.gpg'
#     image_tag: '{{ hostvars[ansible_hostname]["ru_version_tag"][:5] }}EE'    # TO TEST
#     ru_version: '{{ hostvars[ansible_hostname]["ru_version"] }}'   # Development Note: Choosing to set map ru_version to match dbaascli dbhome info output. Might not match OCI standards.
#     patches: '{{ hostvars[ansible_hostname]["patch_numbers"] }}'
#     osdbagrp_groups: '{{ hostvars[ansible_hostname]["osdbagrp_groups"] }}'
#   delegate_to: '{{ fpp_host }}'