
- set_fact:
    wc_name: '{{ hostvars[target_node]["wc_name"] }}'
  when: wc_name is not defined
- set_fact:
    osdbagrp_groups: '{{ hostvars[target_node]["osdbagrp_groups"] }}'
  when: osdbagrp_groups is not defined

- name: 'Add RDBMS Workingcopy {{ wc_name }}'
  include_role:
    name: 'fpp_common'
    tasks_from: 'wc_add.yml'
  vars:
    path: '{{ hostvars[target_node]["oracle_home"] }}'
    add_wc_parameters: '-skipclone -oraclebase {{ hostvars[target_node]["oracle_base"] }} -user oracle'

- name: 'Query RDBMS Workingcopy {{ wc_name }}'
  include_role:
    name: 'fpp_common'
    tasks_from: 'wc_query.yml'