
- set_fact:
    ru_version_tag: '{{ hostvars[hostname]["ru_version"] | regex_replace("\.", "") }}'

- name: 'Add Map File'
  include_role:
    name: 'fpp_common'
    tasks_from: 'create_map_file.yml'
  vars:
    map_dest: '/root/tmp/db/{{ image_name }}.map'
    image_tag: '{{ ru_version_tag[:5] }}EE'
    ru_version: '{{ hostvars[hostname]["ru_version"] }}'
    image_type: 'db'
    patches: '{{ hostvars[hostname]["patch_numbers"] }}'
    groups: '{{ hostvars[hostname]["osdbagrp_names"] }}'