- name: 'Patch Database {{ db_name }}'
  include_role:
    name: 'fpp_common'
    tasks_from: 'patch.yml'
  vars:
    move_type: 'database'
    db_info: '-dbname {{ db_name }}'
    ignorewcpatches: ''
    forcerolling: ''
    eval: '-eval'
  register: 'patch_db_result'
- debug:
    msg: '{{ patch_db_result }}'

- name: 'Patch Database {{ db_name }}'
  include_role:
    name: 'fpp_common'
    tasks_from: 'patch.yml'
  vars:
    move_type: 'database'
    db_info: '-dbname {{ db_name }}'
    ignorewcpatches: ''
    forcerolling: ''
    eval: ''
  register: 'patch_db_result'
- debug:
    msg: '{{ patch_db_result }}'
    
# TO DO: CHECK WC TO SEE IF SUCCESS