
- set_fact:
    osdbagrp_groups: '{{ hostvars[target_node]["osdbagrp_groups"] }}'
  when: osdbagrp_groups is not defined

- name: 'Add GI Workingcopy {{ wc_name }}'
  include_role:
    name: 'fpp_common'
    tasks_from: 'wc_add.yml'
  vars:
    path: '{{ hostvars[target_node]["oracle_home"] }}'
    add_wc_parameters: '-softwareonly'
  register: 'add_gi_wc_result'
- debug:
    msg: '{{ add_gi_wc_result }}'

- name: 'Query GI Workingcopy {{ wc_name }}'
  include_role:
    name: 'fpp_common'
    tasks_from: 'wc_query.yml'
  register: 'query_gi_wc_result'
- debug:
    msg: '{{ query_gi_wc_result }}'