
# Create Individual Map File 

- set_fact:
    ru_version_tag: '{{ grid_version | regex_replace("\.", "") }}'

- name: 'Add Map File'
  include_role:
    name: 'fpp_common'
    tasks_from: 'create_map_file.yml'
  vars:
    image_type: 'grid'
    image_tag: '{{ ru_version_tag[:5] }}EE'
    image: '{{ image_name }}.zip.gpg'
    ru_version: '{{ grid_version }}'
    patches: '{{ hostvars[target_node]["patch_numbers"] }}'
    osdbagrp_groups: '{{ hostvars[target_node]["osdbagrp_groups"] }}'
    image_map_path: 'maps/gi'
