
# When Source is WC 

# - name: 'Set GI Home'
#   include_role:
#     name: 'target_commands'
#     tasks_from: 'gihome_path.yml'
#   when: source_wc is not defined and source_home_flag is defined and source_home_flag == 'true'

- name: 'Patch GI Image'
  import_role:
    name: 'fpp_common'
    tasks_from: 'patch.yml'
  vars:
    target_node: '{{ ansible_hostname }}'
    move_type: 'gihome'
    db_info: ''
    source_info: '-sourcewc {{ source_wc }}'
    dest_info: '-destwc {{ dest_wc }}'
    ignorewcpatches: '-ignorewcpatches'
    forcerolling: ''
    eval: '-eval'
  delegate_to: '{{ fpp_host }}'

- name: 'Patch GI Image'
  import_role:
    name: 'fpp_common'
    tasks_from: 'patch.yml'
  vars:
    target_node: '{{ ansible_hostname }}'
    move_type: 'gihome'
    db_info: ''
    source_info: '-sourcewc {{ source_wc }}'
    dest_info: '-destwc {{ dest_wc }}'
    ignorewcpatches: '-ignorewcpatches'
    forcerolling: ''
    eval: ''
  delegate_to: '{{ fpp_host }}'