
# When Source is WC 

- block:
  - name: 'Patch GI Image'
    include_role:
      name: 'fpp_common'
      tasks_from: 'patch.yml'
    vars:
      move_type: 'gihome'
      db_info: ''
      source_info: '-sourcewc {{ source_wc }}'
      dest_info: '-destwc {{ dest_wc }}'
      ignorewcpatches: '-ignorewcpatches'
      forcerolling: ''
      eval: '-eval'
    register: 'patch_gi_result'
  - debug:
      msg: '{{ patch_gi_result }}'

  - name: 'Patch GI Image'
    include_role:
      name: 'fpp_common'
      tasks_from: 'patch.yml'
    vars:
      move_type: 'gihome'
      db_info: ''
      source_info: '-sourcewc {{ source_wc }}'
      dest_info: '-destwc {{ dest_wc }}'
      ignorewcpatches: '-ignorewcpatches'
      forcerolling: ''
      eval: ''
    register: 'patch_gi_result'
  - debug:
      msg: '{{ patch_gi_result }}'
  when: (source_wc is defined) and (source_home_flag is not defined or source_home_flag == 'false')

# When Source is Current Home

- block:
  - name: 'Patch GI Image'
    include_role:
      name: 'fpp_common'
      tasks_from: 'patch.yml'
    vars:
      move_type: 'gihome'
      db_info: ''
      source_info: '-sourcehome {{ hostvars[target_node]["oracle_home"] }}'
      dest_info: '-destwc {{ dest_wc }}'
      ignorewcpatches: '-ignorewcpatches'
      forcerolling: ''
      eval: '-eval'
    register: 'patch_gi_result'
  - debug:
      msg: '{{ patch_gi_result }}'

  - name: 'Patch GI Image'
    include_role:
      name: 'fpp_common'
      tasks_from: 'patch.yml'
    vars:
      move_type: 'gihome'
      db_info: ''
      source_info: '-sourcehome {{ hostvars[target_node]["oracle_home"] }}'
      dest_info: '-destwc {{ dest_wc }}'
      ignorewcpatches: '-ignorewcpatches'
      forcerolling: ''
      eval: ''
    register: 'patch_gi_result'
  - debug:
      msg: '{{ patch_gi_result }}'
  when: source_wc is not defined and source_home_flag is defined and source_home_flag == 'true'