

- name: 'Patch GI Image'
  include_role:
    name: 'fpp_common'
    tasks_from: 'patch.yml'
  vars:
    move_type: 'gihome'
    db_info: ''
    ignorewcpatches: '-ignorewcpatches'
    forcerolling: ''
    eval: '-eval'
  register: 'patch_gi_result'
- debug:
    msg: '{{ patch_gi_result }}'

- name: 'Patch GI Image'
  include_role:
    name: 'fpp_common'
    tasks_from: 'patch.yml'
  vars:
    move_type: 'gihome'
    db_info: ''
    ignorewcpatches: '-ignorewcpatches'
    forcerolling: ''
    eval: ''
  register: 'patch_gi_result'
- debug:
    msg: '{{ patch_gi_result }}'


# TO DO: Use rhpctl query workingcopy -workingcopy <new WC name>.  The entry for 'Software only' should state 'false'.  Until the move completes it will state true.
