# assert that image is defined

- name: 'Register GI Image {{ image_name }}'
  include_role:
    name: 'fpp_common'
    tasks_from: 'image_register.yml'
  vars:
    map: 'gi/{{ image_name }}.map'
    software_type: 'ORACLEGISOFTWARE'
  register: 'create_gi_image_result'
- debug:
    msg: '{{ create_gi_image_result }}'

- name: 'Query GI Image {{ image_name }}'
  include_role:
    name: 'fpp_common'
    tasks_from: 'query_image.yml'
  register: 'query_gi_image_result'
- debug:
    msg: '{{ query_gi_image_result }}'