

- name: 'Patch GI Image'
  include_role:
    name: 'fpp_common'
    tasks_from: 'patch.yml'
  vars:
    move_type: 'gihome'
    db_info: ''
    ignorewcpatches: '-ignorewcpatches'
    forcerolling: ''
    eval: '-eval'
  register: 'patch_gi_result'
- debug:
    msg: '{{ patch_gi_result }}'

- name: 'Patch GI Image'
  include_role:
    name: 'fpp_common'
    tasks_from: 'patch.yml'
  vars:
    move_type: 'gihome'
    db_info: ''
    ignorewcpatches: '-ignorewcpatches'
    forcerolling: ''
    eval: ''
  register: 'patch_gi_result'
- debug:
    msg: '{{ patch_gi_result }}'


# TO DO: Check working copy to see if successful