user: 'oracle'

name_dict: 
  -a:
    group_name: 'OSASM'
  -d:
    group_name: 'OSDBA'
  -o:
    group_name: 'OSOPER'
  -b:
    group_name: 'OSBACKUP'
  -g:
    group_name: 'OSDG'
  -k:
    group_name: 'OSKM'
  -r:
    group_name: 'OSRAC'

osdbagrp_names: ''

grid_options:
  - '-a'
  - '-d'
  - '-o'

