
- name: 'Assert that vm_cluster_id is defined'
  assert: 
    that: vm_cluster_id is defined
    quiet: 'true'

- name: ExaCC VM Cluster Discovery
  oci_database_vm_cluster_facts:
    vm_cluster_id: '{{ vm_cluster_id }}'
  register: vm_cluster_discovery_result
- debug: { msg: '{{ vm_cluster_discovery_result }}' }
- set_fact: 
    compartment_id: '{{ vm_cluster_discovery_result.vm_clusters[0].compartment_id }}'
  when: vm_cluster_discovery_result.vm_clusters|length == 1
