
- block:
  - name: 'Check FPP RPM'
    shell: |
      rpm -qp {{ fpp_tools_path }}
    register: 'check_fpp_prereq_result'
  - debug: { msg: '{{ check_fpp_prereq_result }}' }
  - set_fact:
      fpp_server_fpptools: '{{ check_fpp_prereq_result.stdout }}'
  run_once: 'true'
  
- name: 'Check Client Prerequisites'
  become: 'true'
  become_user: 'oracle'
  become_method: 'sudo'
  shell: |
    ssh -i {{ identity_file }} -o "StrictHostKeyChecking=no" opc@{{ target_node }} -t "rpm -qa | egrep 'dbaas|FPE|fpptools' ; ls {{ target_mcpostpatch_path }}"
  register: 'check_client_prereq_result'
- debug: { msg: '{{ check_client_prereq_result }}' }

- name: 'Setting dbaas, fpe, and fpptools versions'
  set_fact:
    dbaas_version: '{{ check_client_prereq_result.stdout | regex_findall("dbaas.+?-(.+)\b") | first }}'
    fpe_version: '{{ check_client_prereq_result.stdout | regex_findall("FPE.+?-(.+)\b") | first }}'
    client_server_fpptools: '{{ check_client_prereq_result.stdout | regex_findall("(fpptools.+)\b") | first }}'

- name: 'Assert that dbaas, fpe, and fpp server tools are the correct versions'
  assert:
    that: 
      - dbaas_version is version('1.0-1+21.1.1.3.0_210630.1055', '>=')
      - fpe_version is version('20.1.3-210428.1907', '>=')
      - fpp_server_fpptools == client_server_fpptools
    quiet: 'true'
