- name: 'Copy Template to create Map file'
  become: 'true'
  become_user: 'root'
  become_method: 'sudo'
  template:
    src: 'test_map.json'
    dest: '{{ map_dest }}'

# TO DO: Replace with real map and make sure all values getting passed in