- name: 'Copy Bug List'
  become: 'true'
  become_user: 'oracle'
  become_method: 'sudo'
  shell:  |
    scp -i {{ identity_file }} opc@{{ target_node }}:{{ exa_tmp_path }}/{{ image_name }}_bugs.lst {{ fpp_admin_path }}/{{ image_map_path }}
  register: 'bugs_list_result'
- debug:
    msg: '{{ bugs_list_result }}'

- name: 'Copy Template to create Map file'
  become: 'true'
  become_user: 'root'
  become_method: 'sudo'
  template:
    src: 'map.json'
    dest: '{{ fpp_admin_path }}/{{ image_map_path }}/{{ image_name }}.map'

# Update Master Map File if GI

- block:

  - name: Pull New Map Content From Uploaded File
    become: 'true'
    become_user: 'root'
    become_method: 'sudo'
    slurp:
      src: '{{ fpp_admin_path }}/{{ image_map_path }}/{{ image_name }}.map'    
    register: 'new_image_map'
  - debug:
      msg: '{{ new_image_map.content|b64decode|from_json }}'

  - name: Load Master Map From Container
    become: 'true'
    become_user: 'root'
    become_method: 'sudo'
    shell:
      curl {{ curl_proxy_command }} -o {{ fpp_admin_path }}/{{ image_map_path }}/exa_map {{ container_url }}/exa_map
    register: 'curl_master_map'

  - name: Pull Master Map Content From File
    become: 'true'
    become_user: 'root'
    become_method: 'sudo'
    slurp:
      src: '{{ fpp_admin_path }}/{{ image_map_path }}/exa_map'
    register: 'master_map_data'
  - debug:
      msg: '{{ master_map_data.content|b64decode|from_json }}'

  - name: Appending New GI Map
    set_fact:
      updated_master_map: '{{ master_map_data.content|b64decode|from_json | default([]) | combine(new_image_map.content|b64decode|from_json) }}'
  - debug:
      var: updated_master_map

  - name: Write Master Map Content to File
    become: 'true'
    become_user: 'root'
    become_method: 'sudo'
    copy: 
      content: '{{ updated_master_map | to_nice_json }}'
      dest: '{{ fpp_admin_path }}/{{ image_map_path }}/exa_map'
  - name: Write Master Map File to Container
    become: 'true'
    become_user: 'root'
    shell: 
      curl {{ curl_proxy_command }} -X PUT --data-binary '@{{ fpp_admin_path }}/{{ image_map_path }}/exa_map' {{ container_url }}/exa_map
    register: 'master_map_container'
  - debug:
      msg: '{{ master_map_container }}'

  when: image_type == 'grid'
  