
# db pull path if variable is defined and not in output of check command

# TO DO: cswlib download if not present (should be check first?)
- name: 'cswlib download'
  become: 'true'
  become_user: 'root'
  shell:  |
    /root/bin/dbaascli cswlib download --version {{ dbhome_version }} --bp {{ dbhome_bp }}
  register: 'cswlib_download_result'
- debug:
    msg: '{{ cswlib_download_result }}'

- name: 'create dbhome'
  become: 'true'
  become_user: 'root'
  shell:  |
    /root/bin/dbaascli dbhome create --version {{ dbhome_version }} --bp {{ dbhome_bp }} --ohome_name {{ dbhome_name }} --noprompt YES
  register: 'dbhome_create_result'
- debug:
    msg: '{{ dbhome_create_result }}'