
- set_fact:
    dbhome_version: '{{ version | regex_replace("\.", "") }}'

# TO DO: cswlib download if version not present (should this be checked first? okay to do it everytime? should maybe just do it for image?)

- name: 'cswlib download'
  become: 'true'
  become_user: 'root'
  shell:  |
    /bin/dbaascli cswlib download --version {{ dbhome_version }} --bp {{ dbhome_bp }}
  register: 'cswlib_download_result'
- debug:
    msg: '{{ cswlib_download_result }}'
- set_fact:
    cswlib_download_errors: '{{ cswlib_download_result.stdout | regex_search("ERROR:.+") }}'
- assert:
    that: cswlib_download_errors == ""
    fail_msg: '{{ cswlib_download_errors }}'

- name: 'create dbhome'
  become: 'true'
  become_user: 'root'
  shell:  |
    /bin/dbaascli dbhome create --version {{ dbhome_version }} --bp {{ dbhome_bp }} --ohome_name {{ dbhome_name }} --noprompt YES
  register: 'dbhome_create_result'
- debug:
    msg: '{{ dbhome_create_result }}'

- name: 'check if dbhome created'
  become: 'true'
  become_user: 'root'
  shell:  |
    /bin/dbaascli dbhome info --hname {{ dbhome_name }} --noprompt YES
  register: 'dbhome_info_result'
- debug:
    msg: '{{ dbhome_info_result }}'

- set_fact:
    oracle_home: '{{ dbhome_info_result.stdout | regex_findall("HOME_LOC=(.+?)\n") | first }}'
    ru_version: '{{ dbhome_info_result.stdout | regex_findall("VERSION=(.+?)\n") | first }}'
- debug:
    var: 'oracle_home'
- debug:
    var: 'ru_version'