
# TO DO: cswlib download if version not present (should this be checked first?)
# - name: 'cswlib download'
#   become: 'true'
#   become_user: 'root'
#   shell:  |
#     /bin/dbaascli cswlib download --version {{ dbhome_version }} --bp {{ dbhome_bp }}
#   register: 'cswlib_download_result'
# - debug:
#     msg: '{{ cswlib_download_result }}'

# - name: 'create dbhome'
#   become: 'true'
#   become_user: 'root'
#   shell:  |
#     /bin/dbaascli dbhome create --version {{ dbhome_version }} --bp {{ dbhome_bp }} --ohome_name {{ dbhome_name }} --noprompt YES
#   register: 'dbhome_create_result'
# - debug:
#     msg: '{{ dbhome_create_result }}'

- name: 'check if dbhome created'
  become: 'true'
  become_user: 'root'
  shell:  |
    /bin/dbaascli dbhome info --hname {{ dbhome_name }} --noprompt YES
  register: 'dbhome_info_result'
- debug:
    msg: '{{ dbhome_info_result }}'
- set_fact:
    oracle_home: '{{ dbhome_info_result.stdout | regex_findall("HOME_LOC=(.+?)\n") | first }}'
- debug:
    msg: '{{ oracle_home }}'