
- name: 'purge dbhome'
  become: 'true'
  become_user: 'root'
  shell:  |
    /bin/dbaascli dbhome purge --hname {{ dbhome_name }} --noprompt YES
  register: 'dbhome_purge_result'
- debug:
    msg: '{{ dbhome_purge_result }}'