- name: 'Get Current GI Home'
  become: 'true'
  become_user: 'root'
  become_method: 'sudo'
  shell:  |
    echo $(awk -F : ' $1 ~ /^+ASM[0-9]$/ {print $2}' /etc/oratab)
  register: 'gi_home_result'
- set_fact:
    oracle_home: '{{ gi_home_result.stdout }}'
- debug:
    var: 'oracle_home'

