# TO DO:
# figure out how to finally grid command. How do we find oracle_home of grid home? Is it necessary?
- name: 'Patch GI'
  become: 'true'
  become_user: 'root'
  shell:  |
    /root/bin/dbaascli patch grid upgrade --version {{ grid_version }} --targethome {{ oracle_home }}
  register: 'patched_gi_result'
- debug:
    msg: '{{ patched_gi_result }}'

- name: 'Copy File to Host'
  become: 'true'
  become_user: 'root'
  become_method: 'sudo'
  copy:
    src: 'exclude_file'
    dest: '{{ oracle_home }}'
  register: 'copy_script_result'
- debug:
    msg: '{{ copy_script_result }}'

- name: 'Create Zip File'
  become: 'true'
  become_user: 'root'
  shell:  |
    cd {{ oracle_home }}
    zip -r {{ target_zip_file_path }} .* * -x "..*" -x@{{ oracle_home }}/{{ exclude_file }}
    /bin/gpg --yes --batch --passphrase 'AdbCsPatching$' -c {{ target_zip_file_path }}
  register: 'gi_zip_result'
- debug:
    msg: '{{ gi_zip_result }}'

# TO DO: 
# figure out if container url is a folder (set up as single object right now in map)

- name: 'Upload encrypted image file to object store'
  become: 'true'
  become_user: 'root'
  shell:  |
    curl -T {{ target_zip_file_path }}.gpg {{ storage_url }}
  register: 'upload_result'
- debug:
    msg: '{{ upload_result }}'

