
- name: 'Get Inventory Location'
  become: 'true'
  become_user: 'root'
  become_method: 'sudo'
  shell:  |
    grep inventory_loc /etc/oraInst.loc
  register: 'inventory_result'
- set_fact:
    inventory_path: '{{ inventory_result.stdout | regex_findall("inventory_loc=(.+)") | first }}'
- debug:
    var: 'inventory_path'

- name: 'Get Active Home'
  become: 'true'
  become_user: 'root'
  become_method: 'sudo'
  shell:  |
    grep 'CRS="true"' {{ inventory_path }}/ContentsXML/inventory.xml
  register: 'crs_path_result'
- debug:
    msg: '{{ crs_path_result }}'
- set_fact:
    oracle_home: '{{ crs_path_result.stdout | regex_findall("LOC=.(/.+?). ") | first }}'
- debug:
    var: 'oracle_home'

# - block:
#   - name: 'Get Provided Home For Existing'
#     become: 'true'
#     become_user: 'root'
#     become_method: 'sudo'
#     shell:  |
#       grep '/{{ gi_home_suffix }}"' {{ inventory_path }}/ContentsXML/inventory.xml
#     register: 'home_path_result'
#   - set_fact:
#       gi_home_path_inventory: '{{ home_path_result.stdout | regex_findall("LOC=.(/.+?). ") | first }}'
#     when: home_path_result.stdout != ""
#   when: gi_home_suffix is defined





