# - name: 'Get Current GI Home'
#   become: 'true'
#   become_user: 'root'
#   become_method: 'sudo'
#   shell:  |
#     echo $(awk -F : ' $1 ~ /^+ASM[0-9]$/ {print $2}' /etc/oratab)
#   register: 'gihome_result'
# - set_fact:
#     oracle_home: '{{ gihome_result.stdout }}'
# - debug:
#     var: 'oracle_home'

- name: 'Get Inventory Location'
  become: 'true'
  become_user: 'root'
  become_method: 'sudo'
  shell:  |
    grep inventory_loc /etc/oraInst.loc
  register: 'inventory_result'
- set_fact:
    inventory_path: '{{ inventory_result.stdout | regex_search("inventory_loc=(.+)") }}'

- name: 'Get Provided Home'
  become: 'true'
  become_user: 'root'
  become_method: 'sudo'
  shell:  |
    grep {{ oracle_home }} {{ inventory_path }}/ContentsXML/inventory.xml
  register: 'home_path_result'
  when: oracle_home is defined
- set_fact:
    inventory_path: '{{ home_path_result.stdout | regex_search("inventory_loc=(.+)") }}'

- name: 'Get Active Home'
  become: 'true'
  become_user: 'root'
  become_method: 'sudo'
  shell:  |
    grep 'CRS="true"' {{ inventory_path }}/ContentsXML/inventory.xml
  register: 'home_path_result'
- set_fact:
    home_path: '{{ inventory_result.stdout | regex_search("inventory_loc=(.+)") }}'



