
- name: 'Upgrade GI'
  become: 'true'
  become_user: 'grid'
  become_method: 'sudo'
  shell:  |
    {{ oracle_home }}/bin/oraversion -compositeVersion
  register: 'composite_version_result'
- debug:
    msg: '{{ composite_version_result }}'

# TO DO: Test out Upgrade
# - block:
#   - name: 'Upgrade GI'
#     become: 'true'
#     become_user: 'root'
#     shell:  |
#       {{ dbaascli_path }} patch grid upgrade --version {{ version_tag }} --targethome {{ oracle_home }}
#     register: 'upgrade_gi_result'
#   - debug:
#       msg: '{{ upgrade_gi_result }}'
#   when: composite_version_result.stdout != version_tag