
- name: 'Parse Patch Numbers'
  become: 'true'
  become_user: '{{ target_user }}'
  become_method: 'sudo'
  shell:  |
    $ORACLE_HOME/OPatch/opatch lspatches
  environment:
    ORACLE_HOME: '{{ oracle_home }}'
  register: 'opatch_result'
- debug:
    msg: '{{ opatch_result }}'
- set_fact:
    patches: '{{ opatch_result.stdout_lines | regex_findall("([0-9]{8});", multiline=True) | join(",") }}' 
- debug:
    var: 'patches'

# Bug List

- set_fact:
    exa_bugs_path: '{{ exa_tmp_path }}/{{ image_name }}_bugs.lst'
- name: 'Bug List'
  become: 'true'
  become_user: '{{ target_user }}'
  become_method: 'sudo'
  shell:  |
    $ORACLE_HOME/OPatch/opatch lspatches -bugs > {{ exa_bugs_path }}
  environment:
    ORACLE_HOME: '{{ oracle_home }}'
  register: 'bugs_list_result'
- debug:
    msg: '{{ bugs_list_result }}'

