
- name: 'Group Name Options'
  become: 'true'
  become_user: 'oracle'
  ignore_errors: 'yes'
  shell:  |
    $ORACLE_HOME/bin/osdbagrp h
  environment:
    ORACLE_HOME: '{{ oracle_home }}'
  register: 'osdbagrp_flags'
- debug:
    msg: '{{ osdbagrp_flags }}'
- set_fact:
    osdbagrp_flags_list: '{{ osdbagrp_flags.stderr | regex_findall("-[a-z]") }}'
- debug:
    msg: '{{ osdbagrp_flags_list }}'

- name: 'Group Name Command'
  become: 'true'
  become_user: 'oracle'
  shell:  |
    $ORACLE_HOME/bin/osdbagrp {{ item }}
  environment:
    ORACLE_HOME: '{{ oracle_home }}'
  loop: '{{ osdbagrp_flags_list }}'
  register: 'osdbagrp_names_result'
- debug:
    msg: '{{ osdbagrp_names_result }}'

- name: 'For RDBMS'
  block:
    - name: Add to Map when Possible
      set_fact:
        osdbagrp_names: '{{ osdbagrp_names }}{{ name_dict[item.item].group_name }}={{ item.stdout }},'
      when: item.stdout != ''
      loop: '{{ osdbagrp_names_result.results }}'
  when: image_type == 'db'

- name: 'For Grid'
  block:
    - name: Add to Map when Possible
      set_fact:
        osdbagrp_names: '{{ osdbagrp_names }}{{ name_dict[item.item].group_name }}={{ item.stdout }},'
      when: item.stdout != '' and item.item in grid_options
      loop: '{{ osdbagrp_names_result.results }}'
  when: image_type == 'grid'

- set_fact:
    osdbagrp_names: '{{ osdbagrp_names[:-1] }}'
- debug:
    msg: '{{ osdbagrp_names }}'