

# TO DO: set .oraenv and make sure we have $ORACLE_HOME

# TO DO: GROUP COMMANDS

- name: 'Parse Patch Numbers'
  become: 'true'
  become_user: 'oracle'
  shell:  |
    $ORACLE_HOME/OPatch/opatch lspatches
  register: 'patch_numbers'
- debug:
    msg: '{{ patch_numbers }}'
- set_fact:
    patch_numbers_list: '{{ patch_numbers | regex_findall("^[0-9]+", multiline=True, ignorecase=True) }}'

- name: 'Bug List'
  become: 'true'
  become_user: 'oracle'
  shell:  |
    $ORACLE_HOME/OPatch/opatch lspatches -bugs > /tmp/{{ image_name }}_bugs.lst
    scp /tmp/{{ image_name }}_bugs.lst 
  register: 'bugs_list_result'
- debug:
    msg: '{{ bugs_list_result }}'