- name: 'Get Oracle Home'
  become: 'true'
  become_user: 'root'
  shell:  |
    ORACLE_HOME="$(awk -F : ' $1 ~ /^{{ db_regex }}$/ {print $2}' /etc/oratab)"
    echo $ORACLE_HOME
  register: 'oracle_home_result'
- set_fact:
    oracle_home: '{{ oracle_home_result.stdout }}'
- debug:
    var: 'oracle_home'

