
# TO DO:
# figure out how to define ORACLE_HOME
# figure out if the exclude_file_path is static and can be permanently defined here

- name: 'Create GI Home Zip File'
  become: 'true'
  become_user: 'root'
  shell:  |
    /root/bin/dbaascli patch db apply --patchid {{ patch_id }} --oh {{ patch_oh }} --noprompt YES
    cd $ORACLE_HOME
    zip -r {{ target_zip_file_path }} .* * -x "..*" -x@{{ exclude_file_path }}
    /bin/gpg --yes --batch --passphrase 'AdbCsPatching$' -c {{ target_zip_file_path }}
  register: 'patched_gi_zip_result'
- debug:
    msg: '{{ patched_gi_zip_result }}'

# TO DO: 
# figure out if container url is a folder (set up as single object right now in map)

- name: 'Upload encrypted image file to object store'
  become: 'true'
  become_user: 'root'
  shell:  |
    curl -T {{ target_zip_file_path }}.gpg {{ storage_url }}
  register: 'upload_result'
- debug:
    msg: '{{ upload_result }}'

# TO DO:
# make sure oracle_home defined for map determinations

