
- name: 'patched zip gi'
  become: 'true'
  become_user: 'root'
  shell:  |
    /root/bin/dbaascli patch db apply --patchid {{ patch_id }} --oh {{ patch_oh }} --noprompt YES
    cd $ORACLE_HOME
    zip -r {{ target_zip_file_path }} .* * -x "..*" -x@{{ exclude_file_path }}
    /bin/gpg --yes --batch --passphrase 'AdbCsPatching$' -c {{ target_zip_file_path }}
    curl -T {{ target_zip_file_path }}.gpg {{ storage_url }}
  register: 'patched_gi_zip_result'
- debug:
    msg: '{{ patched_gi_zip_result }}'


# TO DO:
# figure out if ORACLE_HOME IS ALREADY DEFINED BY PREVIOUS ACTION

# figure out what the target_zip_file_path should be / if we can replace it with
# something like /tmp/{{ grid_name }}

# figure out if the exclude_file_path is static and can be permanently defined here