# TO EDIT: fpp paths - check your fpp server for rhpctl executable, maps directory, and a temporary directory
# fpp paths
rhpctl_path: '/u02/app/fpp/fpphome/bin/rhpctl'
fpp_tmp_path: '/u02/app/fpp/admin/tmp'

# maps path note: gi and db expected subdirectory names on FPP server. If using custom names, update image_map_dir values assigned in gi_image_map.yml, rdbms_image_map.yml, gi_image_register,yml, and rdbms_image_register.yml
fpp_maps_path: '/u02/app/fpp/admin/maps'

# -------------------------------------------

# fpp command defaults
ignore_errors_flag: 'no'
curl_https_proxy: ''    # default behavior is no proxy

# patch defaults
eval_param: ''
ignorewcpatches_param: ''
forcerolling_param: ''

# wc defaults
add_wc_param: ''

# delete defaults
metadata_param: ''





