rhpctl_path: '/u02/app/fpp/fpphome/bin/rhpctl'
fpp_admin_path: '/u02/app/fpp/admin'

# patch defaults
eval_param: ''
ignorewcpatches_param: ''
forcerolling_param: ''

# wc defaults
add_wc_param: ''

# delete defaults
metadata_param: ''

ignore_errors_flag: 'no'
curl_https_proxy: ''    # default behavior is no proxy




