- name: 'Find Patch and Bug Data'
  include_role:
    name: 'target_common'
    tasks_from: 'map_data.yml'
  vars:
    target_user: 'grid'

- name: 'Find GI Groups'
  include_role:
    name: 'target_common'
    tasks_from: 'map_groups.yml'
  vars:
    image_type: 'grid'
    target_user: 'grid'

- block: 
  - name: 'Add Map File'
    include_role:
      name: 'fpp_common'
      tasks_from: 'map_file_create.yml'
    vars:
      target_node: '{{ ansible_hostname }}'
      image_type: 'grid'
      image_map_dir: 'gi'     # development note: this should be the default path for grid maps on FPP. If running into errors, may need to update dir name
      image: '{{ image_name }}.zip.gpg'

  - name: 'Update Exa Map File'
    include_role:
      name: 'fpp_common'
      tasks_from: 'map_gi_master_update.yml'
    vars:
      image_map_dir: 'gi'
  delegate_to: '{{ fpp_host }}'
