- name: 'Assert GI Create Image Variables are defined.'
  assert: { that: version is defined and ru_version is defined }

# TO DO: Finalize Fiserv Naming Standards
- set_fact:
    ru_version_tag: '{{ ru_version | regex_replace("\.", "") }}'
- set_fact:
    image_name: 'gihome1_{{ ru_version_tag }}'
  when: image_name is not defined
- debug:
    var: image_name

- name: 'Check if Image {{ image_name }} Exists'
  import_role:
    name: 'fpp_common'
    tasks_from: 'image_query.yml'
  vars:
    ignore_errors_flag: 'yes'
  delegate_to: '{{ fpp_host }}'
- fail:
    msg: 'Image with name {{ image_name }} already exists. Run again with custom image_name provided.'
  when: not query_image_result.stdout | regex_search("does not exist")

- name: 'Set Current GI Home'
  include_role:
    name: 'target_commands'
    tasks_from: 'gihome_path.yml'

# # TO DO: Test out Upgrade
# - name: 'Upgrade GI Home'
#   include_role:
#     name: 'target_commands'
#     tasks_from: 'gihome_upgrade.yml'

- name: 'Zip GI Home'
  include_role:
    name: 'target_commands'
    tasks_from: 'gihome_zip.yml'

- name: 'Create Map File'
  include_role:
    name: 'grid_fpp'
    tasks_from: 'gi_map_create.yml'

- name: 'Register Image'
  include_role:
    name: 'grid_fpp'
    tasks_from: 'gi_image_register.yml'