- name: 'Assert GI Create Image Variables are defined.'
  assert: { that: version is defined and version_tag is defined }

# NAMING STANDARD
- set_fact:
    ru_version_string: '{{ version_tag | regex_replace("\.", "") }}'
- set_fact:
    image_name: 'GI{{ ru_version_string }}'
  when: image_name is not defined
- debug:
    var: image_name

- block:
  - name: 'Check if Image {{ image_name }} Exists'
    include_role:
      name: 'fpp_common'
      tasks_from: 'image_query.yml'
    vars:
      ignore_errors_flag: 'yes'
  - fail:
      msg: 'Image with name {{ image_name }} already exists. Run again with custom image_name provided.'
    when: not query_image_result.stdout | regex_search("does not exist")
  delegate_to: '{{ fpp_host }}'

- name: 'Set Current GI Home'
  include_role:
    name: 'target_commands'
    tasks_from: 'gihome_path.yml'

- assert: { that: oracle_home is defined }

- name: 'Zip GI Home'
  include_role:
    name: 'target_commands'
    tasks_from: 'gihome_zip.yml'

- name: 'Create Map File'
  include_role:
    name: 'grid_fpp'
    tasks_from: 'gi_map_create.yml'

- name: 'Register Image'
  include_role:
    name: 'grid_fpp'
    tasks_from: 'gi_image_register.yml'