# assert that image is defined

- block:
  - name: 'Register GI Image {{ image_name }}'
    include_role:
      name: 'fpp_common'
      tasks_from: 'image_register.yml'
    vars:
      image_map_path: 'maps/gi'
      software_type: '{{ gi_software_type }}'

  - name: 'Query GI Image {{ image_name }}'
    include_role:
      name: 'fpp_common'
      tasks_from: 'image_query.yml'
  delegate_to: '{{ fpp_host }}'