
# Create Individual Map File 

- name: 'Find Patch and Bug Data'
  include_role:
    name: 'target_commands'
    tasks_from: 'map_data.yml'
  vars:
    target_user: 'grid'

- name: 'Find GI Groups'
  include_role:
    name: 'target_commands'
    tasks_from: 'map_groups.yml'
  vars:
    image_type: 'grid'
    target_user: 'grid'

# changed to include
- block: 
  - name: 'Add Map File'
    include_role:
      name: 'fpp_common'
      tasks_from: 'map_file_create.yml'
    vars:
      target_node: '{{ ansible_hostname }}'
      image_type: 'grid'
      image_map_path: 'maps/gi'
      image: '{{ image_name }}.zip.gpg'

  - name: 'Update Exa Map File'
    include_role:
      name: 'fpp_common'
      tasks_from: 'map_gi_master_update.yml'
    vars:
      image_map_path: 'maps/gi'
  delegate_to: '{{ fpp_host }}'
