
- name: 'Assert that patch_error_param is expected value.'
  assert:
    that:
      - patch_error_param == '-revert' or patch_error_param == '-continue'
    quiet: 'true'
  run_once: 'true'
  when: patch_error_param is defined

- name: 'Assert that ignorewcpatches_param is expected value.'
  assert:
    that: ignorewcpatches_param == '-ignorewcpatches' or ignorewcpatches_param == ''
    quiet: 'true'
  run_once: 'true'

- name: 'Assert that forcerolling_param is expected value.'
  assert:
    that: forcerolling_param == '-forcerolling' or forcerolling_param == ''
    quiet: 'true'
  run_once: 'true'

- name: 'Check if Source and Dest WC are valid.'
  block:
  
  - name: 'Check if Source Home is WC'
    include_role:
      name: 'fpp_common'
      tasks_from: 'wc_query.yml'
    vars:
      wc_name: '{{ source_wc }}'

  - name: 'Check if New Home is WC'
    include_role:
      name: 'fpp_common'
      tasks_from: 'wc_query.yml'
    vars:
      wc_name: '{{ dest_wc }}'
    
  run_once: 'true'
  delegate_to: '{{ fpp_host }}'
  when: hostvars[fpp_host]["curr_batch"] is not defined and patch_error_param is not defined


- name: 'Run Pre-Tasks'
  include_role:
    name: 'target_common'
    tasks_from: 'gihome_patch_pretasks.yml'
  when: patch_error_param is not defined


- name: 'Patching Work to Delegate to FPP and Run Once'
  block:

  - name: 'Patch GI Image EVAL'
    include_role:
      name: 'fpp_common'
      tasks_from: 'patch_grid.yml'
    vars:
      eval_param: '-eval'
    when: hostvars[fpp_host]["curr_batch"] is not defined and patch_error_param is not defined
      
  - name: 'Patch GI Image'
    include_role:
      name: 'fpp_common'
      tasks_from: 'patch_grid.yml'
  
  run_once: 'true'
  delegate_to: '{{ fpp_host }}'