
- name: 'Assert additional patch params are expected values if defined'
  assert:
    that:
      - patch_error_param is not defined or (patch_error_param == '-revert' or patch_error_param == '-continue')
      - ignorewcpatches_param is not defined or (ignorewcpatches_param == '-ignorewcpatches' or ignorewcpatches_param == '')
      - forcerolling_param is not defined or (forcerolling_param == '-forcerolling' or forcerolling_param == '')
    quiet: 'true'

- name: 'Check if WCs are valid and run patch eval if on first run'
  block:
  
  - name: 'Check if Source WC exists'
    include_role:
      name: 'fpp_common'
      tasks_from: 'wc_query.yml'
    vars:
      wc_name: '{{ source_wc }}'

  - name: 'Check if Dest WC exists'
    include_role:
      name: 'fpp_common'
      tasks_from: 'wc_query.yml'
    vars:
      wc_name: '{{ dest_wc }}'
  
  - name: 'Patch GI Image EVAL'
    include_role:
      name: 'fpp_common'
      tasks_from: 'patch_grid.yml'
    vars:
      eval_param: '-eval'

  run_once: 'true'
  delegate_to: '{{ fpp_host }}'
  when: hostvars[fpp_host]["curr_batch"] is not defined and patch_error_param is not defined

- name: 'Run Pre-Tasks'
  include_role:
    name: 'target_common'
    tasks_from: 'gihome_patch_pretasks.yml'
  when: patch_error_param is not defined

- block:
  - name: 'Patch GI Image'
    include_role:
      name: 'fpp_common'
      tasks_from: 'patch_grid.yml'
  run_once: 'true'
  delegate_to: '{{ fpp_host }}'