- name: 'Assert GI Create WC Variables are defined.'
  assert: { that: source_wc is defined and dest_wc is defined }

- name: 'Check if Source Home is WC'
  import_role:
    name: 'fpp_common'
    tasks_from: 'wc_query.yml'
  vars:
    wc_name: '{{ source_wc }}'
  delegate_to: '{{ fpp_host }}'

- name: 'Check if New Home is WC'
  import_role:
    name: 'fpp_common'
    tasks_from: 'wc_query.yml'
  vars:
    wc_name: '{{ dest_wc }}'
  delegate_to: '{{ fpp_host }}'

- name: 'Patch GI Image'
  import_role:
    name: 'fpp_common'
    tasks_from: 'patch.yml'
  vars:
    target_node: '{{ ansible_hostname }}'
    move_type: 'gihome'
    db_info: ''
    dest_info: '-destwc {{ dest_wc }}'
    ignorewcpatches: '-ignorewcpatches'
    forcerolling: ''
    eval: '-eval'
  delegate_to: '{{ fpp_host }}'

- name: 'Patch GI Image'
  import_role:
    name: 'fpp_common'
    tasks_from: 'patch.yml'
  vars:
    target_node: '{{ ansible_hostname }}'
    move_type: 'gihome'
    db_info: ''
    dest_info: '-destwc {{ dest_wc }}'
    ignorewcpatches: '-ignorewcpatches'
    forcerolling: ''
    eval: ''
  delegate_to: '{{ fpp_host }}'