
- name: 'Check for Provided Path'
  include_role:
    name: 'target_common'
    tasks_from: 'gihome_check_inventory'
  vars:
    gi_home_inventory: '{{ gi_home_path }}'
- fail:
    msg: 'Path {{ gi_home_path }} has been removed.'
  when: home_path_result.stdout | regex_search("REMOVED=.T.")
- set_fact:
    gi_home_path_inventory: '{{ home_path_result.stdout | regex_findall("LOC=.(/.+?). ") | first }}'
  when: home_path_result.stdout != ""
- debug: { var: gi_home_path_inventory }

- name: 'Assert that gi_home_path exists in inventory.xml'
  assert:
    that: gi_home_path_inventory is defined and gi_home_path == gi_home_path_inventory
    quiet: 'true'

- name: 'Get GI User'
  include_role:
    name: 'target_common'
    tasks_from: 'gihome_user'

# If GI Home is not active, then move software only
- block:
  - name: 'Assert that gi_home_path from inventory is not equal to current active oracle home.'
    assert:
      that: gi_home_path_inventory != oracle_home
      quiet: 'true'
  - name: 'Not the active home: setting swonly'
    set_fact:
      swonly_param: ',swonly'
  when: active_home|bool is false

# If GI Home is currently active, then omit swonly
- block:
  - name: 'Assert that gi_home_path from inventory equals to current active oracle home.'
    assert:
      that: gi_home_path_inventory == oracle_home
      quiet: 'true'
  - name: 'Active home: not setting swonly'
    set_fact:
      swonly_param: ''
  when: active_home|bool is true

- block:
  - name: 'Register GI Workingcopy {{ wc_name }}'
    include_role:
      name: 'fpp_common'
      tasks_from: 'wc_register.yml'
    vars:
      target_node: '{{ ansible_host }}'
      path: '{{ gi_home_path }}'
      user: '{{ gi_user }}'
  delegate_to: '{{ fpp_host }}'