- name: 'Get Provided Home For Existing'
  become: 'true'
  become_user: 'root'
  become_method: 'sudo'
  shell:  |
    grep '/{{ gi_home_path }}"' {{ inventory_path }}/ContentsXML/inventory.xml
  register: 'home_path_result'
- set_fact:
    gi_home_path_inventory: '{{ home_path_result.stdout | regex_findall("LOC=.(/.+?). ") | first }}'
  when: home_path_result.stdout != ""
- assert:
    that: gi_home_path_inventory is defined and gi_home_path == gi_home_path_inventory

# If GI Home is not active, then move software only
- set_fact:
    swonly_param: ',swonly'
  when: gi_home_path_inventory != oracle_home

# If GI Home is currently active, then omit swonly
- set_fact:
    swonly_param: ''
  when: gi_home_path_inventory == oracle_home

# # changed to include
# - block:
#   - name: 'Register GI Workingcopy {{ wc_name }}'
#     include_role:
#       name: 'fpp_common'
#       tasks_from: 'wc_register.yml'
#     vars:
#       target_node: '{{ ansible_hostname }}'
#       path: '{{ gi_home_path }}'
#   delegate_to: '{{ fpp_host }}'