
- name: 'Check for Provided Path'
  include_role:
    name: 'target_common'
    tasks_from: 'gihome_check_inventory'
  vars:
    gi_home_inventory: '{{ gi_home_path }}'
- fail:
    msg: 'Path {{ gi_home_path }} has been removed.'
  when: home_path_result.stdout | regex_search("REMOVED=.T.")
- set_fact:
    gi_home_path_inventory: '{{ home_path_result.stdout | regex_findall("LOC=.(/.+?). ") | first }}'
  when: home_path_result.stdout != ""

- name: 'Assert that gi_home_path exists in inventory.xml'
  assert:
    that: gi_home_path_inventory is defined and gi_home_path == gi_home_path_inventory
    quiet: 'true'

# If GI Home is not active, then move software only
- name: 'Not the active home: setting swonly'
  set_fact:
    swonly_param: ',swonly'
  when: gi_home_path_inventory != oracle_home

# If GI Home is currently active, then omit swonly
- name: 'Active home: not setting swonly'
  set_fact:
    swonly_param: ''
  when: gi_home_path_inventory == oracle_home

- block:
  - name: 'Register GI Workingcopy {{ wc_name }}'
    include_role:
      name: 'fpp_common'
      tasks_from: 'wc_register.yml'
    vars:
      target_node: '{{ ansible_hostname }}'
      path: '{{ gi_home_path }}'
  delegate_to: '{{ fpp_host }}'